cargo-features = ["rename-dependency"]

[package]
name = "cswitch-identity"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]

edition = "2018"

[dependencies]

utils = { path = "../utils", version = "0.1.0", package = "cswitch-utils"}
crypto = { path = "../crypto", version = "0.1.0" , package = "cswitch-crypto"}

# futures = "0.1.25"
# tokio-core = "0.1"
# futures-await = "0.1"
futures-preview = "0.3.0-alpha.9"

[dev-dependencies]

