[package]
name = "cswitch-identity"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]


[dependencies]

cswitch-utils = { path = "../utils", version = "0.1.0" }
cswitch-crypto = { path = "../crypto", version = "0.1.0" }

futures = "0.1.25"
tokio-core = "0.1"
futures-await = "0.1"


[dev-dependencies]

