[package]
name = "cswitch-relay"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]


[dependencies]

cswitch-utils = { path = "../utils", version = "0.1.0" }
cswitch-crypto = { path = "../crypto", version = "0.1.0" }
cswitch-timer = { path = "../timer", version = "0.1.0" }
cswitch-proto = { path = "../proto", version = "0.1.0" }

log = "0.4"

futures = "0.1.25"
tokio-io = "0.1"
tokio-core = "0.1"
futures-await = "0.1"


[dev-dependencies]

