[package]
name = "cswitch-proto"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]
build = "build.rs"

[dependencies]

cswitch-crypto = { path = "../crypto", version = "0.1.0" }

capnp = "0.8"
byteorder = "1.1"

[dev-dependencies]

[build-dependencies]
capnpc = "0.8"
