[package]
name = "cswitch-proto"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]
build = "build.rs"

[dependencies]
log = "0.4"
pretty_env_logger = "0.2"


bytes = "0.4"
capnp = "0.8"

num-bigint = "0.2.0"
num-traits = "0.2.4"

serde = "1"
serde_derive = "1"
serde_json = "1.0.27"
base64 = "0.9"

[dev-dependencies]

[dependencies.byteorder]
version = "1.1"
features = ["i128"]

[build-dependencies]
capnpc = "0.8"
