[package]
name = "offst-proto"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]
build = "build.rs"

[dependencies]

offst-crypto = { path = "../crypto", version = "0.1.0" }
offst-utils = { path = "../common", version = "0.1.0", package = "offst-common" }

capnp = "0.8"
byteorder = "1.1"

serde = "1"
serde_derive = "1"
serde_json = "1.0.27"
bytes = "0.4"

[dev-dependencies]

[build-dependencies]
capnpc = "0.8"
