language: rust
sudo: required
env:
  global:
    - RUST_BACKTRACE: full

git:
  depth: 1

# Don't cache the cargo registry:
# See: https://levans.fr/rust_travis_cache.html
before_cache:
    - trusty/post/cargo-sweep.sh
    - rm -rf $HOME/.cargo/registry

cache:
  directories:
    - $HOME/.cargo
    - $HOME/install

matrix:
  include:

  - env: TARGET=x86_64-unknown-linux-gnu CC=gcc-6 CXX=g++-6 RUSTFLAGS="-C link-dead-code"
    os: linux
    dist: trusty
    rust: nightly-2019-03-20
    addons:
      apt:
        packages:
        - gcc-6
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
    script:
    - trusty/pre/cargo-config.sh
    - trusty/pre/capnp.sh
    - cargo fmt --all -- --check
    - cargo clippy
    - cargo test
    - trusty/post/kcov/try-install.sh
    - trusty/post/kcov/run.sh

  - env: TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly-2019-03-20
    osx_image: xcode9.2
    before_script:
    - brew install capnp
    script:
    - cargo test

  - env: TARGET=x86_64-pc-windows-msvc
    os: windows
    filter_secrets: false
    rust: nightly-2019-03-20
    before_script:
    # We install vcredist2010 as a requirement for the yasm assembler (Used for ring compilation)
    - choco install vcredist2010 capnproto strawberryperl 
    - mkdir -p $HOME/install/yasm
    - curl -o $HOME/install/yasm/yasm.exe https://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
    - export PATH=$HOME/install/yasm:$PATH
    - echo $PATH
    script:
        - cargo test
