language: sh
dist: trusty
sudo: required
git:
  depth: 1
cache:
  cargo: true
  directories:
  - "$HOME/capnp"
  - "$HOME/kcov-x86_64-unknown-linux-gnu"
matrix:
  fast_finish: true
  include:
  - env: RUST_BACKTRACE=1 TARGET=x86_64-pc-windows-msvc
    os: windows
    filter_secrets: false
    # rust: nightly-2019-03-20
    before_script:
    # We install vcredist2010 as a requirement for the yasm assembler (Used for ring compilation)
    - choco install vcredist2010 capnproto strawberryperl 
    - mkdir windows_build_tools
    - curl -o windows_build_tools/yasm.exe https://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
    - export PATH=$PATH:";windows_build_tools"
    - cd
    - echo $PATH
    script:
        - cd
        - yasm
