language: rust
dist: trusty
sudo: required
git:
  depth: 1
cache:
  cargo: true
  directories:
  - "$HOME/capnp"
  - "$HOME/kcov-x86_64-unknown-linux-gnu"
matrix:
  fast_finish: true
  include:
  - env: RUST_BACKTRACE=1 TARGET=x86_64-pc-windows-msvc
    os: windows
    filter_secrets: false
    rust: nightly-2019-03-20
    before_script:
    - travis/windows/before.sh
    script:
    - cargo test
