language: rust
dist: trusty
sudo: required
git:
  depth: 1
cache:
  cargo: true
  directories:
    - $HOME/capnp
    - $HOME/kcov-x86_64-unknown-linux-gnu

matrix:
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu CC=gcc-6 CXX=g++-6 RUSTFLAGS="-C link-dead-code"
      os: linux
      rust: nightly-2019-03-20
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
      script:
        - travis/trusty/pre/cargo-config.sh
        - travis/trusty/pre/capnp.sh
        - cargo fmt --all -- --check
        - cargo clippy
        - cargo test
        - travis/trusty/post/kcov/try-install.sh
        - travis/trusty/post/kcov/run.sh
        - travis/trusty/post/cargo-sweep.sh

    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly-2019-03-20
      osx_image: xcode9.2
      before_script:
        - brew install capnp
      script:
        - cargo test
