
[workspace]

members = [
  "components/funder",
  "components/utils",
  "components/proto",
  "components/crypto",
  "components/identity",
  "components/timer",
  "components/relay",
  "components/secure_channel",
]
