[package]
name = "offst-bin"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]

edition = "2018"

[lib]
name = "bin"
path = "src/lib.rs"

[[bin]]
name = "strelay"
path = "src/bin/strelay.rs"

[[bin]]
name = "stindex"
path = "src/bin/stindex.rs"

[[bin]]
name = "stnode"
path = "src/bin/stnode.rs"

[[bin]]
# OffST Manager
name = "stm"
path = "src/bin/stm.rs"

[dependencies]

common = { path = "../common", version = "0.1.0", package = "offst-common" }
crypto = { path = "../crypto", version = "0.1.0", package = "offst-crypto" }
identity = { path = "../identity", version = "0.1.0" , package = "offst-identity" }
timer = { path = "../timer", version = "0.1.0" , package = "offst-timer" }
proto = { path = "../proto", version = "0.1.0" , package = "offst-proto" }
relay = { path = "../relay", version = "0.1.0" , package = "offst-relay" }
net = { path = "../net", version = "0.1.0" , package = "offst-net" }
index_server = { path = "../index_server", version = "0.1.0" , package = "offst-index-server" }
node = { path = "../node", version = "0.1.0" , package = "offst-node" }
database = { path = "../database", version = "0.1.0" , package = "offst-database" }

toml = "0.4.10"
serde_derive = "1.0.87"
serde = "1.0.87"
base64 = "0.10.1"

clap = "2.32.0"
log = "0.4"
simple_logger = "1.0.1"
futures-preview = "0.3.0-alpha.13"

[dev-dependencies]

tempfile = "3.0.5"

