[package]
name = "offst-node"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]

edition = "2018"

[dependencies]

common = { path = "../common", version = "0.1.0", package = "offst-common" }
crypto = { path = "../crypto", version = "0.1.0", package = "offst-crypto" }
identity = { path = "../identity", version = "0.1.0" , package = "offst-identity" }
timer = { path = "../timer", version = "0.1.0" , package = "offst-timer" }
proto = { path = "../proto", version = "0.1.0" , package = "offst-proto" }
database = { path = "../database", version = "0.1.0" , package = "offst-database" }
funder = { path = "../funder", version = "0.1.0" , package = "offst-funder" }
index_client = { path = "../index_client", version = "0.1.0" , package = "offst-index-client" }

log = "0.4"
futures-preview = "0.3.0-alpha.11"

