[package]
name = "cswitch-secure-channel"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]

[dependencies]

cswitch-utils = { path = "../utils", version = "0.1.0" }
cswitch-crypto = { path = "../crypto", version = "0.1.0" }
cswitch-identity = { path = "../identity", version = "0.1.0" }
cswitch-timer = { path = "../timer", version = "0.1.0" }
cswitch-proto = { path = "../proto", version = "0.1.0" }

log = "0.4"
pretty_env_logger = "0.2"


futures = "0.1.25"
tokio-core = "0.1"
futures-await = "0.1"
byteorder = "1.1"


