cargo-features = ["rename-dependency"]

[package]
name = "cswitch-secure-channel"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]

edition = "2018"

[dependencies]

utils = { path = "../utils", version = "0.1.0", package = "cswitch-utils" }
crypto = { path = "../crypto", version = "0.1.0", package = "cswitch-crypto" }
identity = { path = "../identity", version = "0.1.0" , package = "cswitch-identity"}
timer = { path = "../timer", version = "0.1.0" , package = "cswitch-timer" }
proto = { path = "../proto", version = "0.1.0" , package = "cswitch-proto" }

log = "0.4"
pretty_env_logger = "0.2"

futures-preview = { git = "https://github.com/rust-lang-nursery/futures-rs", rev = "a25e51e" }

# futures = "0.1.25"
# tokio-core = "0.1"
# futures-await = "0.1"
byteorder = "1.1"


