site_name: Offst

# The location of documentation files:
docs_dir: docs

nav:
    - Home: index.md
    - Tutorial: tutorial.md
    - Theory: theory.md
    - Network: network.md


markdown_extensions:
  - footnotes

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
