[package]
name = "cswitch-utils"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]

[dependencies]
log = "0.4"
pretty_env_logger = "0.2"

async_mutex = { git = "https://github.com/realcr/async_mutex", rev = "a1d973ed7" }

rand = "0.5"

bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-codec = "0.1"
futures-await = "0.1"
futures-cpupool = "0.1.8"

capnp = "0.8"

num-bigint = "0.2.0"
num-traits = "0.2.4"

serde = "1"
serde_derive = "1"
serde_json = "1.0.27"
base64 = "0.9"

[dev-dependencies]

[dependencies.byteorder]
version = "1.1"
features = ["i128"]


