[package]
name = "offst-timer"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]
edition = "2018"

[dependencies]

log = "0.4"

bytes = "0.4"
futures-preview = "0.3.0-alpha.10"

utils = { path = "../utils", version = "0.1.0" , package = "offst-utils"}

[dev-dependencies]


